#include "code_generator.hpp"
#include "grammar_helpers.hpp"
#include "grammar_spec.hpp"
#include "parser_action.hpp"
#include "yacc_config.hpp"

bool CodeGenerator::Generate(const Config& config, const GrammarSpec& grammar, std::string& err_msg) {
        std::string pfx = config.sym_prefix;

        // 1. Generate Header File (.tab.h or .h)
        if (config.generate_header || !config.header_file.empty()) {
            std::string header_path = config.header_file;
            if (header_path.empty()) {
                header_path = config.yacc_mode ? "y.tab.h" : GetBaseFilename(config.input_file) + ".tab.h";
            }

            std::ofstream hfile(header_path);
            if (!hfile.is_open()) {
                err_msg = "Could not create header file: " + header_path;
                return false;
            }

            std::string guard = GetBaseFilename(header_path) + "_H_INCLUDED";
            std::transform(guard.begin(), guard.end(), guard.begin(), ::toupper);

            hfile << "/* Automatically generated by yacc C++ Windows CLI Utility */\n";
            hfile << "#ifndef " << guard << "\n";
            hfile << "#define " << guard << "\n\n";

            hfile << "#ifndef " << pfx << "STYPE\n";
            if (!grammar.union_decl.empty()) {
                hfile << "typedef union " << grammar.union_decl << " " << pfx << "STYPE;\n";
            } else {
                hfile << "typedef int " << pfx << "STYPE;\n";
            }
            hfile << "#define " << pfx << "STYPE_IS_DECLARED 1\n";
            hfile << "#endif\n\n";

            hfile << "enum " << pfx << "tokentype {\n";
            bool first = true;
            for (const auto& kv : grammar.symbols) {
                if (!kv.second.is_terminal || kv.first.front() == '\'') continue;
                if (!first) hfile << ",\n";
                hfile << "  " << kv.second.name << " = " << kv.second.value;
                first = false;
            }
            hfile << "\n};\n\n";

            hfile << "extern " << pfx << "STYPE " << pfx << "lval;\n";
            hfile << "int " << pfx << "parse(void);\n";
            hfile << "int " << pfx << "lex(void);\n";
            hfile << "void " << pfx << "error(const char *s);\n\n";

            hfile << "#endif /* " << guard << " */\n";
            if (hfile.fail()) {
                err_msg = "Write error while generating header file: " + header_path;
                hfile.close();
                return false;
            }
            hfile.close();
        }

        // 2. Generate Parser Source File (.tab.c or .c)
        std::string out_path = config.output_file;
        if (out_path.empty()) {
            out_path = config.yacc_mode ? "y.tab.c" : GetBaseFilename(config.input_file) + ".tab.c";
        }

        std::ofstream cfile(out_path);
        if (!cfile.is_open()) {
            err_msg = "Could not create output file: " + out_path;
            return false;
        }

        cfile << "/* High-Speed LALR(1) State Automaton Engine Generated by yacc C++ Utility */\n";
        cfile << "#include <stdio.h>\n";
        cfile << "#include <stdlib.h>\n";
        cfile << "#include <string.h>\n\n";

        cfile << "/* Prologue Code */\n";
        cfile << grammar.prologue << "\n\n";

        cfile << "#ifndef " << pfx << "STYPE\n";
        if (!grammar.union_decl.empty()) {
            cfile << "typedef union " << grammar.union_decl << " " << pfx << "STYPE;\n";
        } else {
            cfile << "typedef int " << pfx << "STYPE;\n";
        }
        cfile << "#endif\n\n";

        cfile << pfx << "STYPE " << pfx << "lval;\n";
        cfile << "int " << pfx << "char = -1;\n";
        cfile << "int " << pfx << "nerrs = 0;\n";
        cfile << "int " << pfx << "debug = " << (config.debug_mode ? "1" : "0") << ";\n\n";

        // Generate Production Rule LHS & Length Lookup Arrays
        cfile << "static const int yyr1[] = { 0";
        for (size_t i = 1; i < grammar.rules.size(); ++i) {
            cfile << ", " << grammar.rules[i].id;
        }
        cfile << " };\n";

        cfile << "static const int yyr2[] = { 0";
        for (size_t i = 1; i < grammar.rules.size(); ++i) {
            cfile << ", " << grammar.rules[i].rhs.size();
        }
        cfile << " };\n\n";

        // Generate Deterministic State Transition Execution Engine
        cfile << "/* LALR(1) State Machine Engine */\n";
        cfile << "#define YYSTACK_INIT_SIZE 256\n";
        cfile << "#define YYMAXDEPTH 1000000\n";
        cfile << "static int yygrowstack(int **yyssa, " << pfx << "STYPE **yyvsa, int *yystack_size, int **yyssp, " << pfx << "STYPE **yyvsp) {\n";
        cfile << "    if (*yystack_size >= YYMAXDEPTH) return 0;\n";
        cfile << "    int used = (int)(*yyssp - *yyssa) + 1;\n";
        cfile << "    int new_size = (*yystack_size < 1) ? YYSTACK_INIT_SIZE : (*yystack_size * 2);\n";
        cfile << "    if (new_size < *yystack_size) return 0;\n";
        cfile << "    if (new_size > YYMAXDEPTH) new_size = YYMAXDEPTH;\n";
        cfile << "    int *new_ss = (int*)malloc((size_t)new_size * sizeof(int));\n";
        cfile << "    " << pfx << "STYPE *new_vs = (" << pfx << "STYPE*)malloc((size_t)new_size * sizeof(" << pfx << "STYPE));\n";
        cfile << "    if (!new_ss || !new_vs) { free(new_ss); free(new_vs); return 0; }\n";
        cfile << "    memcpy(new_ss, *yyssa, (size_t)used * sizeof(int));\n";
        cfile << "    memcpy(new_vs, *yyvsa, (size_t)used * sizeof(" << pfx << "STYPE));\n";
        cfile << "    free(*yyssa);\n";
        cfile << "    free(*yyvsa);\n";
        cfile << "    *yyssa = new_ss;\n";
        cfile << "    *yyvsa = new_vs;\n";
        cfile << "    *yyssp = new_ss + (used - 1);\n";
        cfile << "    *yyvsp = new_vs + (used - 1);\n";
        cfile << "    *yystack_size = new_size;\n";
        cfile << "    return 1;\n";
        cfile << "}\n";
        cfile << "int " << pfx << "parse(void) {\n";
        cfile << "    int yystate = 0;\n";
        cfile << "    int yychar = -1;\n";
        cfile << "    int yystack_size = YYSTACK_INIT_SIZE;\n";
        cfile << "    " << pfx << "STYPE *yyvsa = (" << pfx << "STYPE*)malloc((size_t)yystack_size * sizeof(" << pfx << "STYPE));\n";
        cfile << "    int *yyssa = (int*)malloc((size_t)yystack_size * sizeof(int));\n";
        cfile << "    " << pfx << "STYPE *yyvsp = yyvsa;\n";
        cfile << "    int *yyssp = yyssa;\n";
        cfile << "    int yyerrstatus = 0;\n";
        cfile << "    " << pfx << "STYPE yyval;\n";
        cfile << "    int yylen = 0;\n\n";

        cfile << "    if (!yyvsa || !yyssa) {\n";
        cfile << "        free(yyvsa); free(yyssa);\n";
        cfile << "        " << pfx << "error(\"parser stack allocation failure\");\n";
        cfile << "        return 2;\n";
        cfile << "    }\n\n";

        cfile << "    *yyssp = 0;\n";
        cfile << "    while (1) {\n";
        cfile << "        yystate = *yyssp;\n";
        cfile << "        if (yychar < 0) {\n";
        cfile << "            yychar = " << pfx << "lex();\n";
        cfile << "            if (yychar < 0) yychar = 0;\n";
        cfile << "        }\n\n";

        cfile << "        switch (yystate) {\n";
        for (const auto& st : grammar.states) {
            cfile << "            case " << st.id << ": {\n";
            std::map<int, Action> by_tok;
            bool has_duplicate_tok = false;
            for (const auto& act_kv : st.actions) {
                const std::string& sym_name = act_kv.first;
                auto tok_it = grammar.symbols.find(sym_name);
                if (tok_it == grammar.symbols.end()) {
                    err_msg = "Internal generation error: missing symbol in action table: " + sym_name;
                    cfile.close();
                    return false;
                }
                int tok_val = tok_it->second.value;
                auto ins = by_tok.insert({ tok_val, act_kv.second });
                if (!ins.second) {
                    has_duplicate_tok = true;
                }
            }

            auto emit_action_body = [&](const Action& act) {
                if (act.type == ActionType::SHIFT) {
                    cfile << "                    if ((yyssp - yyssa) >= (yystack_size - 1)) {\n";
                    cfile << "                        if (!yygrowstack(&yyssa, &yyvsa, &yystack_size, &yyssp, &yyvsp)) {\n";
                    cfile << "                            " << pfx << "error(\"parser stack out of memory\");\n";
                    cfile << "                            free(yyvsa); free(yyssa);\n";
                    cfile << "                            return 2;\n";
                    cfile << "                        }\n";
                    cfile << "                    }\n";
                    cfile << "                    yyssp++; yyvsp++;\n";
                    cfile << "                    *yyssp = " << act.target << ";\n";
                    cfile << "                    *yyvsp = " << pfx << "lval;\n";
                    cfile << "                    if (yyerrstatus > 0) yyerrstatus--;\n";
                    cfile << "                    yychar = -1;\n";
                    cfile << "                    continue;\n";
                } else if (act.type == ActionType::REDUCE) {
                    cfile << "                    goto do_reduce_" << act.target << ";\n";
                } else if (act.type == ActionType::ACCEPT) {
                    cfile << "                    free(yyvsa); free(yyssa);\n";
                    cfile << "                    return 0; /* Accept */\n";
                } else {
                    cfile << "                    goto yy_syntax_error;\n";
                }
            };

            if (!has_duplicate_tok && !by_tok.empty()) {
                cfile << "                switch (yychar) {\n";
                for (const auto& kv : by_tok) {
                    cfile << "                case " << kv.first << ":\n";
                    emit_action_body(kv.second);
                    cfile << "                    break;\n";
                }
                cfile << "                default:\n";
                cfile << "                    goto yy_syntax_error;\n";
                cfile << "                }\n";
            } else {
                for (const auto& act_kv : st.actions) {
                    const std::string& sym_name = act_kv.first;
                    const Action& act = act_kv.second;
                    auto tok_it = grammar.symbols.find(sym_name);
                    if (tok_it == grammar.symbols.end()) {
                        err_msg = "Internal generation error: missing symbol in action table: " + sym_name;
                        cfile.close();
                        return false;
                    }
                    int tok_val = tok_it->second.value;

                    cfile << "                if (yychar == " << tok_val << ") {\n";
                    emit_action_body(act);
                    cfile << "                }\n";
                }
            }
            
            cfile << "                goto yy_syntax_error;\n";
            cfile << "            } break;\n";
        }
        cfile << "        }\n\n";

        cfile << "yy_syntax_error:\n";
        cfile << "        " << pfx << "nerrs++;\n";
        cfile << "        " << pfx << "error(\"syntax error\");\n";
        cfile << "        if (yychar == 0) { free(yyvsa); free(yyssa); return 1; }\n";
        cfile << "        while (yyssp >= yyssa) {\n";
        cfile << "            switch (*yyssp) {\n";
        for (const auto& st : grammar.states) {
            auto err_it = st.actions.find("error");
            if (err_it != st.actions.end() && err_it->second.type == ActionType::SHIFT) {
                cfile << "                case " << st.id << ":\n";
                cfile << "                    if ((yyssp - yyssa) >= (yystack_size - 1)) {\n";
                cfile << "                        if (!yygrowstack(&yyssa, &yyvsa, &yystack_size, &yyssp, &yyvsp)) {\n";
                cfile << "                            " << pfx << "error(\"parser stack out of memory\");\n";
                cfile << "                            free(yyvsa); free(yyssa);\n";
                cfile << "                            return 2;\n";
                cfile << "                        }\n";
                cfile << "                    }\n";
                cfile << "                    yyssp++; yyvsp++;\n";
                cfile << "                    *yyssp = " << err_it->second.target << ";\n";
                cfile << "                    yyerrstatus = 3;\n";
                cfile << "                    yychar = -1;\n";
                cfile << "                    goto yy_recovered;\n";
            }
        }
        cfile << "                default: break;\n";
        cfile << "            }\n";
        cfile << "            yyssp--; yyvsp--;\n";
        cfile << "        }\n";
        cfile << "        free(yyvsa); free(yyssa);\n";
        cfile << "        return 1;\n";
        cfile << "yy_recovered:\n";
        cfile << "        continue;\n\n";

        // Reduction Handlers with Relative Stack Reference ($1, $2, $$)
        for (size_t i = 1; i < grammar.rules.size(); ++i) {
            const auto& r = grammar.rules[i];
            cfile << "do_reduce_" << r.id << ": {\n";
            cfile << "    yylen = " << r.rhs.size() << ";\n";
            
            std::string action_code = RewriteSemanticAction(r.action, r.rhs.size());

            if (!Trim(action_code).empty()) {
                cfile << "    " << action_code << "\n";
            }

            cfile << "    yyssp -= yylen;\n";
            cfile << "    yyvsp -= yylen;\n";
            cfile << "    yystate = *yyssp;\n";

            // State GOTO Transitions
            cfile << "    switch (yystate) {\n";
            for (const auto& st : grammar.states) {
                if (st.gotos.count(r.lhs)) {
                    cfile << "        case " << st.id << ": yystate = " << st.gotos.at(r.lhs) << "; break;\n";
                }
            }
            cfile << "    }\n";
            cfile << "    if ((yyssp - yyssa) >= (yystack_size - 1)) {\n";
            cfile << "        if (!yygrowstack(&yyssa, &yyvsa, &yystack_size, &yyssp, &yyvsp)) {\n";
            cfile << "            " << pfx << "error(\"parser stack out of memory\");\n";
            cfile << "            free(yyvsa); free(yyssa);\n";
            cfile << "            return 2;\n";
            cfile << "        }\n";
            cfile << "    }\n";
            cfile << "    yyssp++; yyvsp++;\n";
            cfile << "    *yyssp = yystate;\n";
            cfile << "    *yyvsp = yyval;\n";
            cfile << "    continue;\n";
            cfile << "}\n";
        }

        cfile << "    }\n";
        cfile << "    free(yyvsa); free(yyssa);\n";
        cfile << "    return 0;\n";
        cfile << "}\n\n";

        cfile << "/* Epilogue Code */\n";
        cfile << grammar.epilogue << "\n";
        if (cfile.fail()) {
            err_msg = "Write error while generating parser source file: " + out_path;
            cfile.close();
            return false;
        }
        cfile.close();

        // 3. Generate Detailed State Analysis Report (.output)
        if (config.verbose) {
            std::string vpath = config.verbose_file;
            if (vpath.empty()) {
                vpath = GetBaseFilename(config.input_file) + ".output";
            }

            std::ofstream vfile(vpath);
            if (vfile.is_open()) {
                vfile << "Grammar State Analysis Report - yacc C++ LALR Engine\n";
                vfile << "==============================================================================\n\n";
                if (grammar.shift_reduce_conflicts > 0) {
                    vfile << "State conflicts: " << grammar.shift_reduce_conflicts << " shift/reduce\n";
                }
                if (grammar.reduce_reduce_conflicts > 0) {
                    vfile << "State conflicts: " << grammar.reduce_reduce_conflicts << " reduce/reduce\n";
                }
                vfile << "\nTerminals:\n";
                for (const auto& term : grammar.terminals) {
                    vfile << "  " << term << " (token " << grammar.symbols.at(term).value << ")\n";
                }
                vfile << "\nNonterminals:\n";
                for (const auto& nt : grammar.nonterminals) {
                    vfile << "  " << nt << "\n";
                }
                vfile << "\nProduction Rules:\n";
                for (const auto& r : grammar.rules) {
                    vfile << "  Rule " << r.id << ": " << r.lhs << " -> ";
                    for (const auto& sym : r.rhs) vfile << sym << " ";
                    vfile << "\n";
                }
                vfile << "\n\n";
                vfile << "Automation States:\n";
                vfile << "\n";
                for (const auto& st : grammar.states) {
                    vfile << "\nState " << st.id << ":\n\n";
                    for (const auto& item : st.items) {
                        const auto& r = grammar.rules[item.rule_id];
                        vfile << "  (" << r.id << ") " << r.lhs << " -> ";
                        for (size_t k = 0; k < r.rhs.size(); ++k) {
                            if (k == item.dot) vfile << ". ";
                            vfile << r.rhs[k] << " ";
                        }
                        if (item.dot == r.rhs.size()) vfile << ".";
                        vfile << "\n";
                    }
                    vfile << "\n";
                    for (const auto& act : st.actions) {
                        vfile << "    " << std::left << std::setw(15) << act.first;
                        if (act.second.type == ActionType::SHIFT) vfile << "shift, go to state " << act.second.target << "\n";
                        else if (act.second.type == ActionType::REDUCE) vfile << "reduce using rule " << act.second.target << "\n";
                        else if (act.second.type == ActionType::ACCEPT) vfile << "accept\n";
                        else vfile << "error\n";
                    }
                    for (const auto& gt : st.gotos) {
                        vfile << "    " << std::left << std::setw(15) << gt.first << "go to state " << gt.second << "\n";
                    }
                }
                if (vfile.fail()) {
                    err_msg = "Write error while generating verbose report file: " + vpath;
                    vfile.close();
                    return false;
                }
                vfile.close();
            }
        }

        return true;
    }
