/*
 * BSD 3-Clause License
 *
 * Copyright (c) 2026, Roberto J Dohnert
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of the project nor the names of its contributors may be
 *    used to endorse or promote products derived from this software without
 *    specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * CrossShell for UNIX
 */

#include "automake.hpp"
#include "types.hpp"
#include "utils.hpp"
#include "help.hpp"
#include <iostream>
#include <fstream>
#include <filesystem>

namespace fs = std::filesystem;
using std::string;
using std::vector;
using std::map;
using std::cout;
using std::cerr;
using std::ifstream;
using std::ofstream;

namespace AutomakeModule {

void run_automake(const vector<string>& args) {
    bool add_missing = false;
    bool verbose = false;
    string input_file = "Makefile.am";

    for (size_t i = 0; i < args.size(); ++i) {
        string arg = args[i];
        if (arg == "-h" || arg == "--help") { print_automake_help(); return; }
        else if (arg == "-a" || arg == "--add-missing") add_missing = true;
        else if (arg == "-v" || arg == "--verbose") verbose = true;
        else if (arg[0] != '-') input_file = arg;
    }

    if (!fs::exists(input_file)) {
        cerr << "automake: error: cannot find input file '" << input_file << "'\n";
        return;
    }

    if (add_missing) {
        vector<string> helpers = {"install-sh", "missing", "compile", "depcomp"};
        for (const auto& h : helpers) {
            if (!fs::exists(h)) {
                ofstream out(h);
                out << "#!/bin/sh\n# Helper stub generated by Autotools Enterprise Suite\nexit 0\n";
                if (verbose) cout << "automake: generated helper script '" << h << "'\n";
            }
        }
    }

    ifstream file(input_file);
    AutomakeProject proj;
    string line;
    while (getline(file, line)) {
        string trimmed = trim(line);
        if (trimmed.empty() || trimmed[0] == '#') continue;

        size_t eq = trimmed.find('=');
        if (eq != string::npos) {
            string key = trim(trimmed.substr(0, eq));
            string val = trim(trimmed.substr(eq + 1));
            proj.variables[key] = val;

            if (key == "bin_PROGRAMS") proj.bin_programs = split_words(val);
            else if (key == "SUBDIRS") proj.subdirs = split_words(val);
            else if (key.find("_SOURCES") != string::npos) {
                proj.program_sources[key.substr(0, key.find("_SOURCES"))] = split_words(val);
            } else if (key.find("_LDADD") != string::npos) {
                proj.program_ldadd[key.substr(0, key.find("_LDADD"))] = split_words(val);
            }
        } else {
            proj.raw_rules.push_back(trimmed);
        }
    }

    string out_file = (fs::path(input_file).stem().string() + ".in");
    ofstream out(out_file);
    CompilerType detected_compiler = detect_compiler();
    const bool use_msvc = detected_compiler == CompilerType::MSVC;
    out << "# Makefile.in generated by " << TOOL_NAME << " " << VERSION << "\n\n";
    out << "SHELL = " << (use_msvc ? "cmd.exe" : "/bin/sh") << "\n";
    out << "CC = " << (use_msvc ? "cl.exe" : (detected_compiler == CompilerType::CLANG ? "clang" : "cc")) << "\n";
    out << "CXX = " << (use_msvc ? "cl.exe" : (detected_compiler == CompilerType::CLANG ? "clang++" : "c++")) << "\n";
    out << "CFLAGS = " << (use_msvc ? "/O2" : "-O2") << "\n";
    out << "CXXFLAGS = " << (use_msvc ? "/O2 /EHsc" : "-O2 -fPIC") << "\n";
    out << "EXEEXT = " << (use_msvc ? ".exe" : "") << "\n";
    out << "OBJEXT = " << (use_msvc ? ".obj" : ".o") << "\n\n";

    for (const auto& [k, v] : proj.variables) out << k << " = " << v << "\n";
    out << "\n.PHONY: all clean install\n\nall:";
    for (const auto& p : proj.bin_programs) out << " " << p << "$(EXEEXT)";
    out << "\n\n";

    const string link_flag = use_msvc ? "/Fe$@" : "-o $@";
    const string compile_flag = use_msvc ? "/c $< /Fo$@" : "-c $< -o $@";
    const string clean_prefix = use_msvc ? "\t@if exist " : "\t@rm -f ";
    const string clean_suffix = use_msvc ? " del /F /Q " : "";

    for (const auto& p : proj.bin_programs) {
        out << p << "$(EXEEXT):";
        vector<string> objs;
        if (proj.program_sources.count(p)) {
            for (const auto& s : proj.program_sources[p]) {
                string obj = fs::path(s).stem().string() + "$(OBJEXT)";
                objs.push_back(obj);
                out << " " << obj;
            }
        }
        out << "\n\t$(CXX) $(CXXFLAGS) " << link_flag;
        for (const auto& o : objs) out << " " << o;
        if (proj.program_ldadd.count(p)) {
            for (const auto& ld : proj.program_ldadd[p]) out << " " << ld;
        }
        out << "\n\n";
    }

    out << ".cpp$(OBJEXT):\n\t$(CXX) $(CXXFLAGS) " << compile_flag << "\n\n";
    out << "clean:\n";
    for (const auto& p : proj.bin_programs) {
        if (use_msvc) {
            out << clean_prefix << p << "$(EXEEXT)" << clean_suffix << p << "$(EXEEXT)\n";
        } else {
            out << clean_prefix << p << "$(EXEEXT)\n";
        }
    }

    cout << "automake: successfully created " << out_file << "\n";
}

} // namespace AutomakeModule
